### ISSUE TITLE
Module '"mui-chips-input"' has no exported member 'MuiChipsInput'

### ISSUE THREAD

**Issue by rwdevops999** [viclafouch/mui-chips-input#46] opened 2024-10-11 07:13 UTC
Installing mui-input-chips in a React (18.3) project and including it in the source file (.tsx) I got

import {
  MuiChipsInput,
  type MuiChipsInputChip,
} from 'mui-chips-input';

Module '"mui-chips-input"' has no exported member 'MuiChipsInput'
Module '"mui-chips-input"' has no exported member 'MuiChipsInputChip'

mui-chips-input > dist > index.d.ts contains

export {}

**Expected behavior**
After install, ready to use on React >18.3

**Comment by Arkmind** [comment] 2024-10-15 15:24
Duplicate of [https://github.com/viclafouch/mui-chips-input/issues/43](https://github.com/viclafouch/mui-chips-input/issues/43)

**Comment by ynng3** [comment] 2024-10-16 06:34
Reference of #47

**But, However, this is not an official patch as the creator of this module has not yet made a pull request.**

**Comment by viclafouch** [comment] 2024-10-18 21:39
Hello everyone ! 

This issues has been fixed in [3.1.1](https://github.com/viclafouch/mui-chips-input/releases/tag/v3.1.1).

Sorry for the delay !

**Closed as completed by viclafouch** 2024-10-18 21:39 UTC
